

const moodAffirmations = {
  happy: [
    "Keep shining, your joy is contagious!",
    "Happiness looks great on you. Keep going!",
    "You're glowing from the inside out!",
    "Your joy inspires others.",
    "Let your happiness be a ripple effect.",
    "Today is a gift — you're making the most of it.",
    "You're aligned with the good in your life.",
    "Your smile is a light in the world.",
    "Joy flows effortlessly through you.",
    "You're living in your light.",
    "Celebrate the little moments — they add up.",
    "You're allowed to feel this good.",
    "Keep riding this wave of joy.",
    "This is your sunshine moment — soak it in.",
    "You're creating beautiful memories.",
    "Happiness is your natural state.",
    "You deserve every smile and laugh.",
    "Joy is your power — keep using it.",
    "You’re radiating positive energy.",
    "This happiness is a reflection of your growth.",
    "You're in sync with the universe.",
    "You’re a magnet for good vibes.",
    "Every breath you take is filled with peace.",
    "Your happiness lifts the room.",
    "You are exactly where you need to be.",
    "Today is full of promise and potential.",
    "You’re savoring life beautifully.",
    "You're making happiness your habit.",
    "You’ve earned this joy.",
    "Gratitude enhances your joy.",
    "You’re glowing with good energy.",
    "This joy will carry you far.",
    "Keep spreading your warmth.",
    "Your happy heart is your strength.",
    "Smiles look good on you — wear them proudly.",
    "You're embracing life fully.",
    "Today you laugh with your whole soul.",
    "You’ve unlocked joy from within.",
    "You’re a light for yourself and others.",
    "There is magic in your mood."
  ],
  sad: [
    "It's okay to feel down. Be kind to yourself today.",
    "Storms don’t last forever — this too shall pass.",
    "Your feelings are valid, always.",
    "Healing isn’t linear — take your time.",
    "You’re not alone, even in sadness.",
    "Be gentle with yourself — you're doing your best.",
    "It's okay to rest, to pause, to cry.",
    "This pain is part of your growth.",
    "Your heart is stronger than it feels.",
    "You’ve survived every hard day so far.",
    "Sadness is a sign of your depth.",
    "You are still whole, even when hurting.",
    "Let yourself feel without judgment.",
    "This is a chapter, not your whole story.",
    "You are worthy of compassion.",
    "Tears are healing, not weakness.",
    "You’re allowed to grieve.",
    "Sadness will not define you.",
    "You’re still you, even on heavy days.",
    "Brighter days are on their way.",
    "Take this one breath at a time.",
    "Even now, you are growing.",
    "You don’t have to have it all figured out.",
    "Give yourself grace today.",
    "You’re learning resilience through this.",
    "It’s okay to take a break.",
    "You're doing better than you think.",
    "Hope can live alongside sorrow.",
    "This feeling is not forever.",
    "You are safe to feel this.",
    "Pain is real, and so is your strength.",
    "It’s okay to need support.",
    "Gentleness is strength too.",
    "Let go of what you can’t control.",
    "You don’t have to rush your healing.",
    "You’re not a burden — you’re human.",
    "You’re still making progress.",
    "Even when low, you matter deeply.",
    "This sadness is temporary, not your identity.",
    "You’re still loved — always."
  ],
  anxious: [
    "Breathe in calm, breathe out tension.",
    "You are doing your best. One moment at a time.",
    "This feeling will pass.",
    "You are safe in this moment.",
    "Your breath is your anchor.",
    "You’ve handled this before — you can again.",
    "Let go of what you can’t control.",
    "Worry doesn't define you.",
    "Peace is available to you now.",
    "You’re allowed to slow down.",
    "This moment is manageable.",
    "You are not your thoughts.",
    "You are strong enough for today.",
    "You have the tools to cope.",
    "You are not failing — you’re learning.",
    "You are more than your fear.",
    "Trust your process.",
    "Your mind deserves rest too.",
    "You can return to calm anytime.",
    "This feeling does not control you.",
    "Even now, you are grounded.",
    "Your body knows how to calm itself.",
    "You are worthy of peace.",
    "You’ve come through worse before.",
    "You’re not alone with this.",
    "You’re allowed to ask for help.",
    "Step by step, you’re moving forward.",
    "You’re doing hard things with courage.",
    "Your breath can reset your energy.",
    "Let your body soften — you are safe.",
    "You can sit with discomfort and still be okay.",
    "This too shall pass.",
    "Everything doesn’t have to be perfect.",
    "Progress is peace, not perfection.",
    "You are learning to trust yourself.",
    "One small step is still progress.",
    "You’ve got this, even if it doesn’t feel like it.",
    "You can quiet the noise in your mind.",
    "You are enough, right now.",
    "You are stronger than anxiety."
  ],
  angry: [
    "Take a pause, let the storm pass within.",
    "Your feelings are valid. You are in control.",
    "Anger is a signal, not a sentence.",
    "You can respond, not just react.",
    "Let your breath calm the fire.",
    "You are not your anger.",
    "There’s strength in stillness.",
    "It’s okay to step away and cool off.",
    "You deserve peace of mind.",
    "You can choose a calm response.",
    "Your mind can be your sanctuary.",
    "Let go of what doesn’t serve you.",
    "You are in control of your actions.",
    "Anger fades, clarity remains.",
    "This moment will pass — breathe through it.",
    "You can hold space for your emotions.",
    "You can rise above this.",
    "You are capable of calm leadership.",
    "There is wisdom in your pause.",
    "You can feel without losing yourself.",
    "You are stronger than this spike of rage.",
    "Redirect your energy to healing.",
    "You are grounded and steady.",
    "This heat will cool down soon.",
    "You can choose your peace.",
    "You don’t need to carry this burden.",
    "Release the tension in your body.",
    "You can forgive — yourself and others.",
    "Even in anger, you are kind at heart.",
    "You don’t have to fix it all now.",
    "Let your heart soften.",
    "This is temporary — your values are permanent.",
    "Patience is power.",
    "You can speak with clarity, not fury.",
    "Peace begins with you.",
    "You can return to yourself now.",
    "Compassion calms conflict.",
    "Choose grace over grudges.",
    "You are safe to let go.",
    "You are the calm in the chaos."
  ],
  neutral: [
    "Every day won’t be exciting — and that’s okay.",
    "Small steps matter. You’re moving forward.",
    "Not every moment needs to be productive.",
    "You're steady and centered.",
    "It’s okay to just be today.",
    "Neutral doesn’t mean unimportant.",
    "You are grounded in the present.",
    "Stillness has value too.",
    "Ordinary days build extraordinary lives.",
    "You’re enough, even without doing more.",
    "Routine is a quiet form of growth.",
    "Let today be simple and soft.",
    "Peace often hides in the ordinary.",
    "You’re laying the foundation for tomorrow.",
    "Balance is a gift.",
    "Your calm is your strength.",
    "You’re doing better than you think.",
    "Consistency is powerful.",
    "Even in stillness, you're evolving.",
    "Neutral days make space for clarity.",
    "You’re showing up — that’s what matters.",
    "Life flows in cycles — trust today’s rhythm.",
    "You can breathe, rest, and just exist.",
    "Simplicity is beautiful.",
    "You are not behind.",
    "This moment is enough.",
    "Let yourself enjoy the pause.",
    "You’re safe in this stillness.",
    "Your presence matters.",
    "You are here, and that’s meaningful.",
    "You’re allowed to take a mental break.",
    "Life doesn’t need fireworks to be worthy.",
    "Even slow progress is real progress.",
    "You're doing life at your pace.",
    "You’re aligning with balance.",
    "There is peace in your pace.",
    "You’re walking your path with intention.",
    "Your journey is valid — even now.",
    "Not every day needs to be a breakthrough.",
    "Today, being is enough."
  ],
  excited: [
    "Channel that energy! You're unstoppable today!",
    "This is your time to shine. Go for it!",
    "Let your excitement lead you.",
    "You’re buzzing with possibilities.",
    "Your energy is magnetic today!",
    "Something amazing is unfolding.",
    "You’re on the verge of greatness.",
    "That spark in you is real — chase it!",
    "Go big — this is your moment.",
    "Let your enthusiasm carry you.",
    "Dream boldly, act bravely.",
    "You're building something beautiful.",
    "Today is full of potential.",
    "You’re a force of momentum.",
    "You’re stepping into your purpose.",
    "That inner fire is lighting the way.",
    "Joyful anticipation is a sign of growth.",
    "You’re on a winning streak!",
    "Let your joy overflow into action.",
    "You’re brave enough to leap.",
    "Your ideas are worth the risk.",
    "Fuel your fire with belief.",
    "You’re meant to feel this alive!",
    "Use this energy to inspire others.",
    "You’re breaking through limits.",
    "Celebrate this moment — you’ve earned it.",
    "You're chasing something meaningful.",
    "You're aligned with your passions.",
    "This excitement is your compass.",
    "Your dream life is closer than you think.",
    "You’re in your flow state.",
    "Keep saying yes to opportunity.",
    "Your boldness is beautiful.",
    "You're lit up with purpose.",
    "Stay curious — you're on a roll.",
    "There’s magic in your enthusiasm.",
    "You’re waking up to your own power.",
    "You’re going places — fast!",
    "Your excitement is contagious.",
    "You’re ready. Go for it!"
  ]
};



function getRandomAffirmation(mood) {
  const affirmations = moodAffirmations[mood?.toLowerCase()];
  if (!affirmations || affirmations.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * affirmations.length);
  return affirmations[randomIndex];
}

module.exports = { getRandomAffirmation };
